export const POSTURES = [
  "Sitting",
  "Standing",
  "Dancing",
  "Ceremonial",
  "Meditative",
  "Overflow",
] as const;

export const MATERIALS = [
  "Natural Clay",
  "Shadu",
  "Terracotta",
  "Bronze",
  "Stone",
  "Wood",
  "Gold Leaf",
] as const;

export const TRUNKS = [
  "Upward",
  "Left",
  "Right",
  "S-shaped",
  "Geometric",
  "Flowing",
] as const;

export const OFFERINGS = [
  "Modak",
  "Ukadiche Modak",
  "Lotus",
  "Durva",
  "Diya",
  "Kalash",
  "Mala",
  "Marigold",
] as const;

export type Posture = (typeof POSTURES)[number];
export type Material = (typeof MATERIALS)[number];
export type Trunk = (typeof TRUNKS)[number];
export type Offering = (typeof OFFERINGS)[number];

/** One curated record. Edit these freely in `data/catalogue.ts`. */
export type CatalogueEntry = {
  id: number;
  title: string;
  posture: Posture;
  material: Material;
  trunk: Trunk;
  palette: string;
  mouse: boolean;
  offerings: Offering[];
};

/** A prepared image file, generated by `scripts/prepare-images.mjs`. */
export type Plate = {
  id: number;
  slug: string;
  src: string;
  origin: string;
  width: number;
  height: number;
  blurDataURL: string;
};

/** What the gallery actually renders: plate + catalogue, merged. */
export type Artwork = CatalogueEntry & Omit<Plate, "id">;
